# LiteLLM Configuration with Wildcard Pass-through for Claude Code
# This allows Claude Code to select any model while maintaining observability

model_list:
  # All available Claude models from Anthropic API
  - model_name: "anthropic/*"
    litellm_params:
      model: "anthropic/*"
      api_key: os.environ/ANTHROPIC_API_KEY

litellm_settings:
  # Enable Arize Phoenix callbacks for local observability
  callbacks: ["arize_phoenix"]

  # Don't drop any parameters - preserve everything Claude Code sends
  drop_params: false

  # Enable verbose logging to see what models Claude Code selects
  set_verbose: true

  # Allow pass-through of all parameters
  pass_through_params: true

  # Disable authentication by default (can be overridden with LITELLM_MASTER_KEY)
  disable_auth: true

# Router settings for flexible routing
router_settings:
  routing_strategy: "simple-shuffle"
  # Don't enforce model restrictions
  enable_pre_call_checks: false
  # Disable all health checks that might block models
  disable_cooldowns: true
  allowed_fails: 1000

# Phoenix environment configuration
environment_variables:
  PHOENIX_COLLECTOR_ENDPOINT: "http://phoenix:4317"
  PHOENIX_COLLECTOR_HTTP_ENDPOINT: "http://phoenix:6006/v1/traces"

